# Generated by Django 4.2.2 on 2024-02-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0004_alter_user_cedula_cohorte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSignature', models.CharField(max_length=60)),
            ],
        ),
    ]
